### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Roger-Breton** [collinswakholi/ColorCorrectionGUI#1]
I tried to run the code. After loading the TestImage.TIFF, I pressed the Run button: I drew the rectangle correspoinding to the chart and waited... At that point, I got a nice series of error messages:

Warning: Image Processing Toolbox is not found. Use 'getrect' to get coordinate. 
> In checker2colors (line 116)
In color_calib_UI>run_color_corr_Callback (line 153)
In gui_mainfcn (line 95)
In color_calib_UI (line 43)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)color_calib_UI('run_color_corr_Callback',hObject,eventdata,guidata(hObject))
In color_calib_UI>gamma_val_Callback (line 358)
In gui_mainfcn (line 95)
In color_calib_UI (line 43)
In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)color_calib_UI('gamma_val_Callback',hObject,eventdata,guidata(hObject)) 
Error using getrect
Interruption during mouse selection.

Error in checker2colors (line 117)
                vertex_pts = bbox2points(getrect(hfig));

Error in color_calib_UI>run_color_corr_Callback (line 153)
[my_RGB, coords] = checker2colors(Im_ref, patch_size,...

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in color_calib_UI (line 43)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)color_calib_UI('run_color_corr_Callback',hObject,eventdata,guidata(hObject))
 
Error using color_calib_UI>gamma_val_Callback
Error while evaluating UIControl Callback.

**Comment by Roger-Breton** [comment]
I must add I'm running 2023a. I seeme to remember support for Guides was going to be progressively dropped from Matlab?  And I think the error message suggest the use of the 'getrect' function to get coordinate instead?

**Comment by Roger-Breton** [comment]
The problem seems to occur in this line of code: "vertex_pts = bbox2points(hrect.Position);" in checker2colors.m::

hint_str = 'Drag a rectangle to exactly cover the 4 corners of the color checker.';
            [~, hfig] = colorcheckerimshow(checker_img, hint_str, param.scale, param.gamma);
            try 
                hrect = drawrectangle('Label', 'Color Checker Rectangle');
                vertex_pts = bbox2points(hrect.Position);
            catch
                warning('Image Processing Toolbox is not found. Use ''getrect'' to get coordinate.');
                vertex_pts = bbox2points(getrect(hfig));
            end

Where is this "bbox2points" function coming from?

**Comment by Roger-Breton** [comment]
A chatGPT search indicates that the bbox2points() function is part of the Computer Vision Toolbox? Which I don't have.

**Comment by Roger-Breton** [comment]
I installed the ComputerVision Toolbox and problem solved!

**Comment by collinswakholi** [comment]
Yeah, it looks like it was an error with the Image Processing Toolbox, I am glad you fixed it.

**Comment by Roger-Breton** [comment]
Another issue is "errors" in the 'spd'?
The data for he D65 illuminant is not correct. At 560nm, the value should be 0.001000 and it is 0.009463? The whole spd is offsetted too low. 
An other issue is "Why the choice of Illuminant" in the main window? And it should be clear that the illuminant is used to calculate the tristimulus values. This is a serious deficiency. This program maybe 'interesting' but it is so poorly documented? I have not checked the spectral reflectances but the fact that they were measured with an X-Rite SP64, which I have, is kind of dumb? But that's what it is. Whoever wrote this code is extremely knowledgeable in Matlab. But in order to be of any use, the author should have anticipated that the user would want to load its own spectral reflectances from one's own ColorChecker chart. And even allow to load XYZ values instead of going through the needless complexities of using spectral reflectances. I wonder what the story of this code it? 
BTW, it was NOT an error with the Image Processing Toolbox: it was an error because my Matlab could not find the Computer Vision Toolbox from which the bbpoints was derived from. It sould be indicated as a requirement.

**Comment by Roger-Breton** [comment]
I found the refered link. Sorry I missed that information.
https://github.com/QiuJueqin/color-correction-toolbox
